library/urls.py
from django.urls import path, include
from . import views

app_name = 'library'

urlpatterns = [
    path('', views.index, name='index'),
    path('authors/', views.authors, name='authors'),
    path('author/<int:author_id>/', views.author, name='author'),
    path('books/', views.BookListView.as_view(), name='books'),
    path('book/<int:pk>/', views.BookDetailView.as_view(), name='book_detail'),
    path('search/', views.search, name='search'),
    path('mybooks/', views.LoanedBooksByUserListView.as_view(), name='my_borrowed'),
    path('register/', views.register, name='register')

]

mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
    path('learning/', include('learning.urls')),
    path('', RedirectView.as_view(url='/learning/')),
    path('library/', include('library.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('autoservice/', include('autoservice.urls')),
    path('users/', include('users.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = 'Tinklapio valdymas'

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('profile/', views.profile, name='profile'),
    path('about/', views.about, name='about'),
    path('facebook_login/', views.facebook_login, name='facebook_login'),
    path('google_login/', views.google_login, name='google_login'),

]

library/models.py
from django.db import models
from django.urls import reverse
import uuid
from django.contrib.auth.models import User
from datetime import date
from tinymce.models import HTMLField



from django.db import models
class Genre(models.Model):
    name = models.CharField('Pavadinimas', max_length=200, help_text='Įveskite knygos žanrą (pvz. detektyvas)')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Žanras'
        verbose_name_plural = 'Žanrai'

class Book(models.Model):
    """Modelis reprezentuoja knygą (bet ne specifinę knygos kopiją)"""
    title = models.CharField('Pavadinimas', max_length=200)
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True, related_name='books')
    summary = models.TextField('Aprašymas', max_length=1000, help_text='Trumpas knygos aprašymas')
    isbn = models.CharField('ISBN', max_length=13, help_text='13 Simbolių <a href="https://www.isbn-international.org/content/what-isbn">ISBN kodas</a>')
    genre = models.ManyToManyField(Genre, help_text='Išrinkite žanrą(us) šiai knygai')
    cover = models.ImageField('Viršelis', upload_to='covers', null=True, blank=True)

    def __str__(self):
        return self.title

    def display_genre(self):
        return ', '.join(genre.name for genre in self.genre.all()[:3])

    display_genre.short_description = 'Žanras'

    class Meta:
        verbose_name = 'Knyga'
        verbose_name_plural = 'Knygos'

class BookInstance(models.Model):
    """Modelis, aprašantis konkrečios knygos kopijos būseną"""
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='Unikalus ID knygos kopijai')
    book = models.ForeignKey('Book', on_delete=models.SET_NULL, null=True, verbose_name='Knyga')
    due_back = models.DateField('Bus prieinama', null=True, blank=True)
    reader = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, verbose_name='Skaitytojas')

    LOAN_STATUS = (
        ('a', 'Administruojama'),
        ('p', 'Paimta'),
        ('g', 'Galima paimti'),
        ('r', 'Rezervuota'),
    )
    status = models.CharField(
        max_length=1,
        choices=LOAN_STATUS,
        blank=True,
        default='a',
        help_text='Statusas', verbose_name='Statusas'
    )
    class Meta:
        ordering = ['due_back']
        verbose_name = 'Knygos egzempliorius'
        verbose_name_plural = 'Knygos egzemplioriai'


    def __str__(self):
        return f'{self.id} ({self.book.title if self.book else "Nėra knygos"})'

    @property
    def is_overdue(self):
        if self.due_back and date.today() > self.due_back:
            return True
        return False

class Author(models.Model):
    """Modelis, atvaizduojantis autorių."""
    first_name = models.CharField('Vardas', max_length=100)
    last_name = models.CharField('Pavardė', max_length=100)
    description = HTMLField('Aprašymas', default='')


    class Meta:
        ordering = ['last_name', 'first_name']
    def __str__(self):
        """Eilutė, atvaizduojanti Modelio objektą."""
        return f'{self.last_name} {self.first_name}'

    def display_books(self):
        return ', '.join(book.title for book in self.books.all()[:3])

    display_books.short_description = 'Knygos'

    class Meta:
        verbose_name = 'Autorius'
        verbose_name_plural = 'Autoriai'

library/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Book, Author, BookInstance, Genre
from django.shortcuts import render, get_object_or_404
from django.views import generic
from django.core.paginator import Paginator
from django.db.models import Q
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect
from django.contrib.auth.forms import User
from django.views.decorators.csrf import csrf_protect
from django.contrib import messages



def index(request):
    num_books = Book.objects.all().count()
    num_instances = BookInstance.objects.all().count()
    num_instances_available = BookInstance.objects.filter(status__exact='g').count()
    num_authors = Author.objects.count()
    num_visits = request.session.get('num_visits', 1)
    request.session['num_visits'] = num_visits + 1

    context = {
        'num_books': num_books,
        'num_instances': num_instances,
        'num_instances_available': num_instances_available,
        'num_authors': num_authors,
        'num_visits': num_visits
    }
    return render(request, 'library/index.html', context=context)

def authors(request):
    paginator = Paginator(Author.objects.all(), 5)
    page_number = request.GET.get('page')
    authors = paginator.get_page(page_number)
    context = {
        'authors': authors
    }
    return render(request, 'library/authors.html', context=context)

def author(request, author_id):
    single_author = get_object_or_404(Author, pk=author_id)
    return render(request, 'library/author.html', {'author': single_author})

class BookListView(generic.ListView):
    model = Book
    paginate_by = 5
    template_name = 'library/book_list.html'

class BookDetailView(generic.DetailView):
    model = Book
    template_name = 'library/book_detail.html'

def search(request):
    """
    paprasta paieška. query ima informaciją iš paieškos laukelio,
    search_results prafiltruoja pagal įvestą tekstą knygų pavadinimus ir aprašymus.
    Icontains nuo contains skiriasi tuo, kad icontains ignoruoja ar raidės
    didžiosios/mažosios.
    """
    query = request.GET.get('query')
    search_results = Book.objects.filter(Q(title__icontains=query) | Q(summary__icontains=query))
    return render(request, 'library/search.html', {'books': search_results, 'query': query})

class LoanedBooksByUserListView(LoginRequiredMixin,generic.ListView):
    model = BookInstance
    template_name ='library/user_books.html'
    paginate_by = 5

    def get_queryset(self):
        return BookInstance.objects.filter(reader=self.request.user).filter(status__exact='p').order_by('due_back')

@csrf_protect
def register(request):
    if request.method == "POST":
        # pasiimame reikšmes iš registracijos formos
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']
        password2 = request.POST['password2']
        # tikriname, ar sutampa slaptažodžiai
        if password == password2:
            # tikriname, ar neužimtas username
            if User.objects.filter(username=username).exists():
                messages.error(request, f'Vartotojo vardas {username} užimtas!')
                return redirect('register')
            else:
                # tikriname, ar nėra tokio pat email
                if User.objects.filter(email=email).exists():
                    messages.error(request, f'Vartotojas su el. paštu {email} jau užregistruotas!')
                    return redirect('register')
                else:
                    # jeigu viskas tvarkoje, sukuriame naują vartotoją
                    User.objects.create_user(username=username, email=email, password=password)
                    messages.info(request, f'Vartotojas {username} užregistruotas!')
                    return redirect('login')
        else:
            messages.error(request, 'Slaptažodžiai nesutampa!')
            return redirect('register')
    return render(request, 'library/register.html')

library/templates/library/author.html
{% extends "base.html" %}
{% block title %}Biblioteka{% endblock %}

{% block content %}
    <div class="container author">
    <h4>{{ author.first_name }} {{ author.last_name }}</h4>
    <hr/>
    <p>{{ author.description|safe }}</p>
    <h5>Mes turime šias {{ author.first_name }} {{ author.last_name }} knygas:</h5>
    <ul>
        {% for i in author.books.all %}
            <li>{{ i.title }}</li>

        {% endfor %}
    </ul>
    </div>
{% endblock %}

library/templates/library/authors.html
{% extends "base.html" %}
{% block title %}Biblioteka{% endblock %}

{% block content %}
    <h1>Autoriai</h1>
    <p>Mūsų knygų autorių sąrašas.</p>
    {% for a in authors %}
        <li><a href="{% url 'library:author' a.id %}">{{ a.first_name }} {{ a.last_name }}</a></li>    {% endfor %}
    <div class="container puslapiai">
        <nav aria-label="...">
            {% if authors.has_other_pages %}
                <ul class="pagination pagination-sm justify-content-end">
                    {% for i in authors.paginator.page_range %}
                        {% if authors.number == i %}
                            <li class="page-item active">
                                <a class="page-link">{{ i }}</a>
                            </li>
                        {% else %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{ i }}">{{ i }}</a>
                            </li>
                        {% endif %}
                    {% endfor %}
                </ul>
            {% endif %}
        </nav>
    </div>
{% endblock %}

library/templates/library/book_detail.html
{% extends "base.html" %}
{% block title %}Biblioteka{% endblock %}

{% block content %}
    {% if book.cover %}
        <img src="{{ book.cover.url }}" style="width: 300px; height: auto; margin-bottom: 20px;">
    {% endif %}
    <h1>{{ book.title }}</h1>
    <p><strong>Autorius:</strong> <a href="{% url 'library:author' book.author.pk %}">{{ book.author }}</a></p>
    <p><strong>Aprašymas:</strong> {{ book.summary }}</p>
    <p><strong>ISBN:</strong> {{ book.isbn }}</p>
    <p><strong>Žanras:</strong> {{ book.genre.all|join:", " }}</p>
    <div style="margin-left:20px;margin-top:20px">
        <h4>Egzemplioriai:</h4>
        {% for copy in book.bookinstance_set.all %}
            <hr>
            <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}">
                {{ copy.get_status_display }}
            </p>
            {% if copy.status != 'a' %}
                <p><strong>Bus grąžinta:</strong> {{ copy.due_back }}</p>
            {% endif %}
            <p class="text-muted"><strong>Id:</strong> {{ copy.id }}</p>
        {% endfor %}
    </div>
{% endblock %}

library/templates/library/book_list.html
{% extends "base.html" %}
{% block title %}Knygų sąrašas{% endblock %}

{% load static %}
{% block content %}
    <h1>Knygų sąrašas</h1>
    {% if book_list %}
        <div class="row">
            {% for book in book_list %}
                <div class="col-md-4 d-flex align-items-stretch">
                    <div class="card mb-4 shadow-sm">
                        {% if book.cover %}
                            <img src="{{ book.cover.url }}" class="card-img-top" alt="..." style="width: 300px; height: auto; margin-bottom: 20px;">
                        {% else %}
                            <img src="{% static 'img/no-image.png' %}" class="card-img-top">
                        {% endif %}
                        <div class="card-body">
                            <ul>
                                <a href="{% url 'library:book_detail' book.pk %}">{{ book.title }}</a>
                                ({{ bookinst.due_back }})<br>
                            </ul>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% else %}
        <p>Bibliotekoje knygų nėra.</p>
    {% endif %}
    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; pirmas</a>
                <a href="?page={{ page_obj.previous_page_number }}">atgal</a>
            {% endif %}
            <span class="current">
                {{ page_obj.number }} iš {{ page_obj.paginator.num_pages }}
            </span>
            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">pirmyn</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">paskutinis &raquo;</a>
            {% endif %}
        </span>
    </div>
{% endblock %}

library/templates/library/index.html
{% extends "base.html" %}
{% block title %}Biblioteka{% endblock %}
{% block content %}
  {% if messages %}
    {% for message in messages %}
        <div class="alert alert-{% if message.tags == 'error' %}danger{% elif message.tags == 'info' %}success{% endif %}" role="alert">
                {{ message }}
        </div>
    {% endfor %}
  {% endif %}
  <h1>Rajono biblioteka</h1>
  <p>Sveiki atvykę į knygų rojų!</p>

    <ul class="navbar-nav mx-2">
        <li class="nav-item active"><a class="nav-link" href="{% url 'library:index' %}">Pradžia</a></li>
        <li class="nav-item active"><a class="nav-link" style="color: black;" href="{% url 'library:books' %}">Visos knygos</a></li>
        <li class="nav-item active"><a class="nav-link" style="color: black;" href="{% url 'library:authors' %}">Visi autoriai</a></li>
        {% if user.is_authenticated %}
            <li class="nav-item"><a class="nav-link" href="#">
              <svg class="bi bi-person" width="1.5em" height="1.5em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd" d="M13 14s1 0 1-1-1-4-6-4-6 3-6 4 1 1 1 1h10zm-9.995-.944v-.002.002zM3.022 13h9.956a.274.274 0 00.014-.002l.008-.002c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664a1.05 1.05 0 00.022.004zm9.974.056v-.002.002zM8 7a2 2 0 100-4 2 2 0 000 4zm3-2a3 3 0 11-6 0 3 3 0 016 0z" clip-rule="evenodd"/>
              </svg>
            {{ user.get_username }}</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'library:my_borrowed'%}">Mano knygos</a></li>
            <li class="nav-item">
              <form method="post" action="{% url 'logout' %}">
                {% csrf_token %}
                <button type="submit">Atsijungti</button>
              </form>
            </li>
        {% else %}
    <li class="nav-item"><a class="nav-link" href="{% url 'login'%}">Prisijungti</a></li>
    <li class="nav-item"><a class="nav-link" href="{% url 'library:register'%}">Registruotis</a></li>
{% endif %}
    </ul>
    <hr>
    <p>Šiuo metu turime:</p>
  <ul>
    <li><strong>Knygų:</strong> {{ num_books }}</li>
    <li><strong>Egzempliorių:</strong> {{ num_instances }}</li>
    <li><strong>Laisvų egzempliorių:</strong> {{ num_instances_available }}</li>
    <li><strong>Autorių:</strong> {{ num_authors }}</li>
  </ul>
    <br>
    <p>Čia jūs lankotes {{ num_visits }}-ą kartą.</p>
{% endblock %}

library/templates/library/register.html
{% extends "base.html" %}

{% block content %}

    <div class="container register">
        <h3>Registracija</h3><br/>
        <form method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="username">Vartotojo vardas</label>
                <input name="username" type="text" class="form-control" id="username" aria-describedby="usernameHelp">
                <small id="usernameHelp" class="form-text text-muted">Iki 150 simbolių.</small>
            </div>
            <div class="form-group">
                <label for="exampleInputEmail1">El. paštas</label>
                <input name="email" type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
                <small id="emailHelp" class="form-text text-muted">Nesidalinsime su niekuo, nesiųsime jokio spamo.
                    Reikalingas naujam slaptažodžiui išsiųsti. </small>
            </div>
            <div class="form-group">
                <label for="password">Slaptažodis</label>
                <input name="password" type="password" class="form-control" id="password" aria-describedby="pwdHelp">
                <small id="pwdHelp" class="form-text text-muted">Ne mažiau, kaip 8 simboliai. Negali būti vien tik
                    skaičiai</small>
            </div>
            <div class="form-group">
                <label for="password2">Pakartoti slaptažodį</label>
                <input name="password2" type="password" class="form-control" id="password2" aria-describedby="pwd2Help">
            </div>
            <button type="submit" class="btn btn-primary register-button">Registruotis</button>
        </form>
        <p>Jeigu užsiregistravote anksčiau, <a href="/login"><strong>prisijunkite.</strong></a></p>
    </div>

{% endblock %}

library/templates/library/search.html
{% extends "base.html" %}
{% block title %}Biblioteka{% endblock %}

{% block content %}
  <h1>Paieškos pagal "{{query}}" rezultatai:</h1>
  </br>
  {% if books %}
  <ul>
    {% for book in books %}
      <li>
        <a href="{{ book.id }}">{{ book.title }}</a> ({{book.author}})
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>Oops. Nieko neradome :(</p>
  {% endif %}
  {% endblock %}

library/templates/library/user_books.html
{% extends "base.html" %}
{% block title %}Biblioteka{% endblock %}

{% block content %}
    <h1>Mano paimtos knygos</h1>
    {% if bookinstance_list %}
    <ul>
      {% for bookinst in bookinstance_list %}
      <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'library:book_detail' bookinst.book.pk %}">{{bookinst.book.title}}</a> ({{ bookinst.due_back }})
      </li>
      {% endfor %}
    </ul>
    {% else %}
      <p>Šiuo metu iš mūsų nesate paėmę knygų.</p>
    {% endif %}      
{% endblock %}