learning/urls.py
from django.urls import path
from . import views

app_name = 'learning'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),

    path('categories/', views.CategoryListView.as_view(), name='categories'),
    path('category/<int:pk>', views.CategoryDetailView.as_view(), name='category_detail'),

    path('python/', views.PythonListView.as_view(), name='python'),
    path('python/<int:pk>', views.PythonDetailView.as_view(), name='python_detail'),

    path('django/', views.DjangoListView.as_view(), name='django'),
    path('django/<int:pk>', views.DjangoDetailView.as_view(), name='django_detail'),

    path('tasks/', views.TaskListView.as_view(), name='task_list'),
    path('task/<int:pk>', views.TaskDetailView.as_view(), name='task_detail'),

]

mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
    path('learning/', include('learning.urls')),
    path('', RedirectView.as_view(url='/learning/')),
    path('library/', include('library.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('autoservice/', include('autoservice.urls')),
    path('users/', include('users.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = 'Tinklapio valdymas'

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('profile/', views.profile, name='profile'),
    path('about/', views.about, name='about'),
    path('facebook_login/', views.facebook_login, name='facebook_login'),
    path('google_login/', views.google_login, name='google_login'),

]

learning/models.py
from django.db import models
from tinymce.models import HTMLField

class Category(models.Model):
    name = models.CharField(max_length=100, verbose_name='Pavadinimas')
    content = HTMLField(blank=True, null=True, verbose_name='Turinys')
    image = models.ImageField(upload_to='images/', blank=True, null=True, verbose_name='Paveikslėlis')

    class Meta:
        verbose_name = 'Programavimo kalba'
        verbose_name_plural = 'Programavimo kalbos'

    def __str__(self):
        return self.name


class Python(models.Model):
    title = models.CharField(max_length=100, verbose_name='Pavadinimas')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Kategorija')
    content = HTMLField(blank=True, null=True, verbose_name='Turinys')
    image = models.ImageField(upload_to='images/', blank=True, null=True, verbose_name='Paveikslėlis')

    class Meta:
        ordering = ['title']
        verbose_name = 'Python'
        verbose_name_plural = 'Python'

    def __str__(self):
        return self.title


class Django(models.Model):
    title = models.CharField(max_length=100, verbose_name='Pavadinimas')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Kategorija')
    content = HTMLField(blank=True, null=True, verbose_name='Turinys')
    image = models.ImageField(upload_to='images/', blank=True, null=True, verbose_name='Paveikslėlis')

    class Meta:
        ordering = ['title']
        verbose_name = 'Django'
        verbose_name_plural = 'Django'

    def __str__(self):
        return self.title


class Task(models.Model):
    class QType(models.TextChoices):
        TEXT = 'TXT', 'Tekstas'
        RADIO = 'RADIO', 'Vienas pasirinkimas'
        CHECKBOX = 'CHECKBOX', 'Daug pasirinkimų'

    qtype = models.CharField(max_length=10, choices=QType.choices, default=QType.RADIO, verbose_name='Tipas')
    title = models.CharField(max_length=100, verbose_name='Pavadinimas')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Kategorija')
    question = HTMLField(blank=True, null=True, verbose_name='Užduotis')

    class Meta:
        ordering = ['title']
        verbose_name = 'Užduotis'
        verbose_name_plural = 'Užduotys'

    def __str__(self):
        return self.title


class Answer(models.Model):
    task = models.ForeignKey(Task, on_delete=models.CASCADE, verbose_name='Užduotis')
    option = models.CharField(max_length=100, verbose_name='Variantas')
    is_correct = models.BooleanField(default=False, verbose_name='Teisingas')

    class Meta:
        verbose_name = 'Atsakymas'
        verbose_name_plural = 'Atsakymai'

    def __str__(self):
        return self.option

learning/forms.py
from django import forms

class NumberedRadioSelect(forms.RadioSelect):
    def create_option(self, name, value, label, selected, index, subindex=None, attrs=None):
        option = super().create_option(name, value, label, selected, index, subindex=subindex, attrs=attrs)
        option['label'] = f"{index + 1}. {option['label']}"
        return option

class AnswerForm(forms.Form):
    answer = forms.ChoiceField(
        label='Jūsų pasirinkimas:',
        widget=NumberedRadioSelect
    )

    def __init__(self, *args, answer_choices=None, **kwargs):
        if answer_choices is None:
            answer_choices = []
        super().__init__(*args, **kwargs)
        self.fields['answer'].choices = answer_choices

learning/views.py
from django.shortcuts import render
from django.views import generic
from django.urls import reverse
from .models import Category, Python, Django, Task
from .forms import AnswerForm

class IndexView(generic.TemplateView):
    template_name = 'learning/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['num_categories'] = Category.objects.count()
        context['num_python'] = Python.objects.count()
        context['num_django'] = Django.objects.count()
        context['num_tasks'] = Task.objects.count()
        context['num_visits'] = self.request.session.get('num_visits', 0)
        self.request.session['num_visits'] = context['num_visits'] + 1

        return context

class CategoryListView(generic.ListView):
    model = Category
    context_object_name = 'category_list'
    template_name = 'learning/category_list.html'

class CategoryDetailView(generic.DetailView):
    model = Category
    context_object_name = 'category'
    template_name = 'learning/category_detail.html'

class PythonListView(generic.ListView):
    model = Python
    context_object_name = 'python_list'
    template_name = 'learning/python_list.html'
    paginate_by = 5  # Nustatykite puslapio dydį

    def get_queryset(self):
        queryset = super().get_queryset()
        search_query = self.request.GET.get('search', '')
        if search_query:
            queryset = queryset.filter(title__icontains=search_query)
        return queryset

class PythonDetailView(generic.DetailView):
    model = Python
    context_object_name = 'python'
    template_name = 'learning/python_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['previous_python'] = Python.objects.filter(id__lt=self.object.id).order_by('-id').first()
        context['next_python'] = Python.objects.filter(id__gt=self.object.id).order_by('id').first()
        return context

class DjangoListView(generic.ListView):
    model = Django
    context_object_name = 'django_list'
    template_name = 'learning/django_list.html'

class DjangoDetailView(generic.DetailView):
    model = Django
    context_object_name = 'django'
    template_name = 'learning/django_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['previous_django'] = Django.objects.filter(id__lt=self.object.id).order_by('-id').first()
        context['next_django'] = Django.objects.filter(id__gt=self.object.id).order_by('id').first()
        return context

class TaskListView(generic.ListView):
    model = Task
    context_object_name = 'tasks'
    template_name = 'learning/task_list.html'

class TaskDetailView(generic.DetailView):
    model = Task
    context_object_name = 'task'
    template_name = 'learning/task_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        answer_choices = [(answer.option, answer.option) for answer in self.object.answer_set.all()]
        context['form'] = AnswerForm(answer_choices=answer_choices)
        next_task = Task.objects.filter(id__gt=self.object.id).order_by('id').first()
        context['next_task_id'] = next_task.id if next_task else None
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        answer_choices = [(answer.option, answer.option) for answer in self.object.answer_set.all()]
        form = AnswerForm(request.POST, answer_choices=answer_choices)

        if form.is_valid():
            answer = form.cleaned_data['answer']
            correct_answers = self.object.answer_set.filter(is_correct=True)
            result, color = self.evaluate_answer(answer, correct_answers)
            next_task = Task.objects.filter(id__gt=self.object.id).order_by('id').first()
            next_task_id = next_task.id if next_task else None
            return render(request, 'learning/result.html',
                          {'result': result, 'color': color, 'next_task_id': next_task_id,
                           'current_task_id': self.object.id})
        else:
            return render(request, 'learning/task_detail.html', {'task': self.object, 'form': form})

    def evaluate_answer(self, answer, correct_answers):
        if any(correct_answer.option == answer for correct_answer in correct_answers):
            return 'Teisingai', 'green'
        else:
            return 'Neteisingai, bandykite dar kartą', 'red'

learning/templates/learning/category_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}{{ category.name }}{% endblock %}

{% block content %}
    <h2>{{ category.name }}</h2>

    {% if category.content %}
    <p>{{ category.content | safe }}</p>
    {% endif %}

    <hr>
    <a class="btn btn-primary" href="javascript:history.back()">Grįžti</a>

    {% if category.name == "Python" %}
    <a class="btn btn-secondary" href="{% url 'learning:python' %}">Pereiti prie Python teorijos</a>
    {% elif category.name == "Django" %}
    <a class="btn btn-secondary" href="{% url 'learning:django' %}">Pereiti prie Django teorijos</a>
    {% endif %}
{% endblock %}

learning/templates/learning/category_list.html
{% extends "base.html" %}
{% load static %}

{% block title %}Programavimo kalbos{% endblock %}

{% block content %}
    <div class="container">
        <h1 class="mt-4 mb-3">Programavimo kalbos</h1>

        <div class="row">
            {% for category in category_list %}
                <div class="col-md-4 mb-4">
                    <div class="card h-100">
                        {% if category.image %}
                            <img class="card-img-top" src="{{ category.image.url }}" alt="{{ category.name }}">
                        {% endif %}
                        <div class="card-body">
                            <h5 class="card-title">
                                <a href="{% url 'learning:category_detail' category.id %}">{{ category.name }}</a>
                            </h5>
                            {% if category.content %}
                                <p class="card-text">{{ category.content|truncatechars:100|safe }}</p>
                            {% endif %}
                            <div class="d-flex">
                                <a href="{% url 'learning:category_detail' category.id %}" class="btn btn-link ml-auto">Plačiau</a>
                            </div>

                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
    <a href="{% url 'learning:index' %}" class="btn btn-primary">Į pradžią</a>
{% endblock %}

learning/templates/learning/django_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}{{ django.title }}{% endblock title %}

{% block content %}

<style>

</style>

{% if django.content %}
    <p>{{ django.content | safe }}</p>
{% endif %}

{% if django.image %}
    <img class="img-fluid rounded" src="{{ django.image.url }}" alt="{{ django.title }}" style="max-width: 100%; height: auto;">
{% endif %}
<hr>

<div class="button-area d-flex">
    <a class="btn custom-btn-primary mr-2" href="{% url 'learning:django_detail' previous_django.id %}">Atgal</a>
    <a class="btn custom-btn-secondary mr-auto" href="{% url 'learning:index' %}">Į pradžią</a>
    {% if next_django %}
        <a class="btn custom-btn-primary ml-auto" href="{% url 'learning:django_detail' next_django.id %}">Pirmyn</a>
    {% endif %}
</div>

{% block footer %}
{% endblock footer %}

{% endblock content %}

learning/templates/learning/django_list.html
{% extends "base.html" %}
{% load static %}

{% block title %}Django temos{% endblock %}

{% block content %}
<div class="container">
    <h2 class="mt-4 mb-3">Django temos</h2>
<br>
<hr>
    {% for django in django_list %}
        <div class="col-md-12 mb-4">
            <div class="py-2">
                <h5 class="text-truncate">
                    {% if django.image %}
                        <img class="img-fluid rounded mr-3" src="{{ django.image.url }}" alt="{{ django.title }}" style="width: 60px; height: auto;">
                    {% endif %}
                    <a href="{% url 'learning:django_detail' django.id %}">{{ django.title }}</a>
                </h5>
            </div>
            <hr>
        </div>
    {% endfor %}
</div>
    <a href="{% url 'learning:index' %}" class="btn btn-primary">Atgal</a>
            <a class="btn btn-secondary" href="{% url 'learning:index' %}">Į pradžią</a>

{% endblock %}

learning/templates/learning/index.html
{% extends "base.html" %}
{% load static %}

{% block title %}Pagrindinis puslapis{% endblock %}

{% block content %}
<div class="container">
    <div class="jumbotron mt-3">
        <h1 class="display-4">Sveiki atvykę į mūsų svetainę!</h1>
        <p class="lead">Šioje svetainėje yra:</p>
        <hr class="my-4">
        <div class="row">
            <div class="col-md-3 mb-3">
                <div class="card">
                    <div class="card-body text-center">
                        <h5 class="card-title">{{ num_categories }} programavimo kalbų</h5>
                        <a href="{% url 'learning:categories' %}" class="btn btn-primary">Peržiūrėti</a>
                    </div>
                </div>
            </div>
            <div class="col-md-3 mb-3">
                <div class="card">
                    <div class="card-body text-center">
                        <h5 class="card-title">{{ num_python }} Python temų</h5>
                        <a href="{% url 'learning:python' %}" class="btn btn-primary">Peržiūrėti</a>
                    </div>
                </div>
            </div>
            <div class="col-md-3 mb-3">
                <div class="card">
                    <div class="card-body text-center">
                        <h5 class="card-title">{{ num_django }} Django temų</h5>
                        <a href="{% url 'learning:django' %}" class="btn btn-primary">Peržiūrėti</a>
                    </div>
                </div>
            </div>
            <div class="col-md-3 mb-3">
                <div class="card">
                    <div class="card-body text-center">
                        <h5 class="card-title">{{ num_tasks }} užduočių</h5>
                        <a href="{% url 'learning:task_list' %}" class="btn btn-primary">Peržiūrėti</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <p class="text-center">Ši svetainė buvo aplankyta {{ num_visits }} kartų.</p>
</div>
{% endblock %}

learning/templates/learning/python_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}{{ python.title }}{% endblock title %}

{% block content %}

<style>

</style>

{% if python.content %}
    <p>{{ python.content | safe }}</p>
{% endif %}

{% if python.image %}
    <img class="img-fluid rounded" src="{{ python.image.url }}" alt="{{ python.title }}" style="max-width: 100%; height: auto;">
{% endif %}
<hr>

<div class="button-area d-flex">
    <a class="btn custom-btn-primary mr-2" href="{% url 'learning:python_detail' previous_python.id %}">Atgal</a>
    <a class="btn custom-btn-secondary mr-auto" href="{% url 'learning:index' %}">Į pradžią</a>
    {% if next_python %}
        <a class="btn custom-btn-primary ml-auto" href="{% url 'learning:python_detail' next_python.id %}">Pirmyn</a>
    {% endif %}
</div>


{% block footer %}
{% endblock footer %}

{% endblock content %}

learning/templates/learning/python_list.html
{% extends "base.html" %}
{% load static %}

{% block title %}Python temos{% endblock %}

{% block content %}
<div class="container">
    <h2 class="mt-4 mb-3">Python temos</h2>
<br>
<hr>
    {% for python in python_list %}
        <div class="col-md-12 mb-4">
            <div class="py-2">
                <h5 class="text-truncate">
                    {% if python.image %}
                        <img class="img-fluid rounded mr-3" src="{{ python.image.url }}" alt="{{ python.title }}" style="width: 60px; height: auto;">
                    {% endif %}
                    <a href="{% url 'learning:python_detail' python.id %}">{{ python.title }}</a>
                </h5>
            </div>
            <hr>
        </div>
    {% endfor %}
</div>
    <a href="{% url 'learning:index' %}" class="btn btn-primary">Atgal</a>
            <a class="btn btn-secondary" href="{% url 'learning:index' %}">Į pradžią</a>

{% endblock %}

learning/templates/learning/result.html
{% extends "base.html" %}
{% load static %}

{% block title %}Rezultatas{% endblock %}

{% block content %}
<div class="container mt-4">
    <h2>Rezultatas</h2>
    <hr>
    <div class="mt-4">
        {% if color == 'green' %}
            <h3 class="text-success">Teisingai!</h3>
        {% else %}
            <h3 class="text-danger">Atsakymas neteisingas, bandykite dar kartą.</h3>
        {% endif %}
    </div>
    <div class="mt-4">
        <a href="{% url 'learning:task_list' %}" class="btn btn-primary">Grįžti prie užduočių sąrašo</a>
        <a href="{% url 'learning:task_detail' current_task_id %}" class="btn btn-secondary ml-2">Grįžti į tą pačią</a>
        {% if next_task_id %}
            <a href="{% url 'learning:task_detail' next_task_id %}" class="btn btn-secondary ml-2">Pereiti prie sekančios</a>
        {% endif %}
    </div>
</div>
     {% block footer %}
       {% endblock footer %}
{% endblock %}

learning/templates/learning/task_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}{{ task.title }}{% endblock %}

{% block content %}
<div class="container mt-4">
    <h2>{{ task.title }}</h2>
    <hr>
    {% if task.question %}
        <div class="card mb-3">
            <div class="card-body" style="background-color: #f8f9fa;">
                {{ task.question|safe }}
            </div>
        </div>
        <hr>
    {% endif %}

    <form method="post" class="mb-4">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-success">Pateikti atsakymą</button>
    </form>

    <a class="btn btn-primary" href="{% url 'learning:task_list' %}" class="btn btn-primary">Grįžti</a>

</div>
{% endblock %}

learning/templates/learning/task_list.html
{% extends "base.html" %}
{% load static %}

{% block title %}Užduotys{% endblock %}

{% block content %}
<div class="container">
    <h2 class="mt-4 mb-3">Užduotys</h2>
    <hr>
    {% for task in tasks %}
        <div class="row mb-4">
            <div class="col-md-12">
                <div class="d-flex align-items-center py-2">
                    {% if task.image %}
                        <img class="img-fluid rounded mr-3" src="{{ task.image.url }}" alt="{{ task.title }}" style="width: 60px; height: auto;">
                    {% endif %}
                    <h5 class="text-truncate mb-0">
                        <a href="{% url 'learning:task_detail' task.id %}">{{ task.title }}</a>
                    </h5>
                </div>
                <hr>
            </div>
        </div>
    {% endfor %}
    <div class="d-flex justify-content-between">
        <a href="{% url 'learning:index' %}" class="btn btn-primary">Grįžti</a>
        <a class="btn btn-secondary" href="{% url 'learning:index' %}">Į pradžią</a>
    </div>
</div>
{% endblock %}