autoservice/urls.py
from django.urls import path
from . import views

app_name = 'autoservice'

urlpatterns = [
    path('', views.index, name='index'),
    path('cars/', views.CarListView.as_view(), name='cars'),
    path('car/<int:pk>', views.CarDetailView.as_view(), name='car_detail'),
    path('services/', views.ServiceListView.as_view(), name='services'),
    path('service/<int:pk>', views.ServiceDetailView.as_view(), name='service_detail'),
    path('orders/', views.OrderListView.as_view(), name='orders'),
    path('order/<int:pk>', views.OrderDetailView.as_view(), name='order_detail'),
    ]

mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
    path('learning/', include('learning.urls')),
    path('', RedirectView.as_view(url='/learning/')),
    path('library/', include('library.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('autoservice/', include('autoservice.urls')),
    path('users/', include('users.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = 'Tinklapio valdymas'

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('profile/', views.profile, name='profile'),
    path('about/', views.about, name='about'),
    path('facebook_login/', views.facebook_login, name='facebook_login'),
    path('google_login/', views.google_login, name='google_login'),

]

autoservice/models.py
from django.db import models


class Service(models.Model):
    name = models.CharField(max_length=200, verbose_name='Paslauga')
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Kaina')

    def __str__(self):
        return f'{self.name} {self.price}'

    class Meta:
        verbose_name_plural = 'Paslaugos'


class Order(models.Model):
    car = models.ForeignKey('Car', on_delete=models.CASCADE, verbose_name='Automobilis')
    date = models.DateField(verbose_name='Data')
    total_sum = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Bendra suma')

    def __str__(self):
        return f'{self.car} {self.date}  {self.total_sum}'

    class Meta:
        verbose_name_plural = 'Užsakymai'


class OrderService(models.Model):
    service = models.ForeignKey(Service, on_delete=models.CASCADE, verbose_name='Užsakoma paslauga')
    quantity = models.IntegerField(verbose_name='Kiekis')
    order = models.ForeignKey('Order', on_delete=models.CASCADE, verbose_name='Užsakymas')

    STATUS_AUTO = (
        ('v', 'Vykdoma'),
        ('b', 'Baigta'),
        ('e', 'Eilėje'),
    )
    status = models.CharField(max_length=1, choices=STATUS_AUTO, default='e', verbose_name='Statusas', blank=True, null=True)

    def __str__(self):
        return f'{self.service}'

    class Meta:
        ordering = ['status']
        verbose_name_plural = 'Užsakytos paslaugos'


class Car(models.Model):
    client = models.CharField(max_length=200, verbose_name='Klientas')
    license_plate = models.CharField(max_length=20, verbose_name='Valstybinis numeris')
    VIN_code = models.CharField(max_length=20, verbose_name='VIN kodas')
    year = models.IntegerField(verbose_name='Metai')
    brand = models.CharField(max_length=200, verbose_name='Markė')
    model = models.CharField(max_length=200, verbose_name='Modelis')
    image = models.ImageField(upload_to='images/', null=True, blank=True, verbose_name='Paveikslėlis')

    def __str__(self):
        return f'{self.client} {self.brand} {self.model} '

    class Meta:
        verbose_name_plural = 'Automobiliai'

autoservice/views.py
from django.shortcuts import render
from .models import Car, Service, Order
from django.views import generic


def index(request):
    num_cars = Car.objects.all().count()
    num_services = Service.objects.all().count()
    num_orders = Order.objects.all().count()
    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits + 1

    context = {
        'num_cars': num_cars,
        'num_services': num_services,
        'num_orders': num_orders,
        'num_visits': num_visits,
    }

    return render(request, 'autoservice/index.html', context=context)

class CarListView(generic.ListView):
    model = Car
    paginate_by = 5
    template_name = 'autoservice/car_list.html'


class CarDetailView(generic.DetailView):
    model = Car
    template_name = 'autoservice/car_detail.html'

class ServiceListView(generic.ListView):
    model = Service
    template_name = 'autoservice/service_list.html'

class ServiceDetailView(generic.DetailView):
    model = Service
    template_name = 'autoservice/service_detail.html'

class OrderListView(generic.ListView):
    model = Order
    paginate_by = 4
    template_name = 'autoservice/order_list.html'

class OrderDetailView(generic.DetailView):
    model = Order
    template_name = 'autoservice/order_detail.html'

autoservice/templates/autoservice/car_detail.html
{% extends "base.html" %}

{% block content %}
    <div class="container my-5">
        <div class="card">
            <div class="card-header bg-primary text-white">
                <h2 class="my-4">{{ car.brand }} {{ car.model }}</h2>
            </div>
            <div class="card-body">
                {% if car.image %}
                    <img src="{{ car.image.url }}" alt="{{ car.brand }} {{ car.model }}"
                         style="width: 300px; height: auto; margin-bottom: 20px;">
                {% endif %}
                <h5 class="card-title">Automobilio informacija:</h5>
                <p class="card-text"><strong>Klientas:</strong> {{ car.client }}</p>
                <p class="card-text"><strong>Valstybinis numeris:</strong> {{ car.license_plate }}</p>
                <p class="card-text"><strong>VIN kadas:</strong> {{ car.VIN_code }}</p>
                <hr>
                <h5 class="card-title">Aprašymas:</h5>
                <!-- Assuming you have a description field in your Car model -->
                <p>{{ car.description | safe }}</p>
                <hr>
            </div>
        </div>
        <a href="{% url 'autoservice:cars' %}" class="btn btn-primary">Grįžti į automobilių sąrašą</a>
    </div>
{% endblock %}

autoservice/templates/autoservice/car_list.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <h1 class="my-4">Automobiliai</h1>
        <div class="list-group">
            {% for car in page_obj %}
                <a href="{% url 'autoservice:car_detail' car.pk %}" class="list-group-item list-group-item-action">
                    {% if car.image %}
                        <img src="{{ car.image.url }}" alt="{{ car.brand }} {{ car.model }}"
                             style="width: 300px; height: auto; margin-bottom: 20px;">
                    {% endif %}
                    {{ car.brand }} {{ car.model }} ({{ car.year }})
                </a>
            {% empty %}
            {% endfor %}
        </div>
        <div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; Pirmas</a>
            <a href="?page={{ page_obj.previous_page_number }}">atgal</a>
        {% endif %}

        <span class="current">
            Puslapis {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">kitas</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">Paskutinis &raquo;</a>
        {% endif %}
    </span>
        </div>
    </div>
{% endblock %}

autoservice/templates/autoservice/index.html
{% extends 'base.html' %}
{% block title %}Autoservisas{% endblock %}

{% block content %}
<div class="container">
 <ul class="navbar-nav mx-2">
        <li class="nav-item active"><a class="nav-link" href="{% url 'autoservice:index' %}">Pradžia</a></li>
        <li class="nav-item active"><a class="nav-link" style="color: black;" href="{% url 'autoservice:cars' %}">Visi automobiliai</a></li>
        <li class="nav-item active"><a class="nav-link" style="color: black;" href="{% url 'autoservice:services' %}">Visos paslaugos</a></li>

     <hr>
  <h1 class="my-4 text-center">Statistika</h1>
  <div class="row">
    <div class="col-md-4">
      <div class="card text-white bg-primary mb-3">
        <div class="card-header text-center" style="color: black;"><i class="fas fa-tools"></i> Šiuo metu teikiame paslaugų</div>
        <div class="card-body">
          <h5 class="card-title text-center">{{ num_services }}</h5>
        </div>
      </div>
    </div>
    <div class="col-md-4">
      <div class="card text-white bg-success mb-3">
        <div class="card-header text-center" style="color: black;"><i class="fas fa-check-circle"></i> Vykdomi užsakymai</div>
        <div class="card-body">
          <h5 class="card-title text-center">{{ num_orders }}</h5>
        </div>
      </div>
    </div>
    <div class="col-md-4">
      <div class="card text-white bg-info mb-3">
        <div class="card-header text-center" style="color: black;"><i class="fas fa-car"></i> Registruoti automobiliai</div>
        <div class="card-body">
          <h5 class="card-title text-center">{{ num_cars }}</h5>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <div class="card text-center">
        <div class="card-body">
          <p class="card-text">Jūs apsilankėte šiame puslapyje {{ num_visits }} kartų.</p>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

autoservice/templates/autoservice/order_detail.html
{% extends "base.html" %}

{% block content %}
<div class="container">
  <div class="card">
    <div class="card-header">
      <h2>Užsakymas Nr. {{ uzsakymas.pk }}</h2>
    </div>
    <div class="card-body">
      <p><i class="fas fa-calendar-alt"></i> Data: <strong>{{ uzsakymas.data }}</strong></p>
      <p><i class="fas fa-car"></i> Automobilis: <strong>{{ uzsakymas.automobilis }}</strong></p>
      <p><i class="fas fa-euro-sign"></i> Bendra suma: <strong>{{ uzsakymas.bendra_suma }}</strong> €</p>
      <p><i class="fas fa-clipboard-check"></i> Statusas: <strong>{{ uzsakymas.get_statusas_display }}</strong></p>
      <h3><i class="fas fa-tools"></i> Užsakymo paslaugos:</h3>

      <ul class="list-group">
        {% for uzsakymo_paslauga in uzsakymas.uzsakymopaslauga_set.all %}
        <li class="list-group-item">{{ uzsakymo_paslauga.paslauga }} - {{ uzsakymo_paslauga.kiekis }} vnt. - {{ uzsakymo_paslauga.kaina }} €</li>
        {% empty %}
        <li class="list-group-item">Nėra paslaugų.</li>
        {% endfor %}
      </ul>
    </div>
  </div>
</div>
{% endblock %}

autoservice/templates/autoservice/order_list.html
{% extends "base.html" %}

{% block content %}
<div class="container">
  <h3 class="my-4">Užsakymai</h3>
  {% for uzsakymas in page_obj %}
  <div class="card mb-3">
    <div class="card-body">
      <h5 class="card-title"><a href="{% url 'uzsakymas_detail' uzsakymas.pk %}">{{ uzsakymas }}</a></h5>
      <p class="card-text"><i class="fas fa-calendar-alt"></i> Data: <strong>{{ uzsakymas.data }}</strong></p>
<p class="card-text"><i class="fas fa-clipboard-check"></i> Statusas: <strong>{{ uzsakymas.get_statusas_display }}</strong></p>    </div>
  </div>
  {% empty %}
  <div class="alert alert-warning" role="alert">
    Nėra užsakymų.
  </div>
  {% endfor %}
  <div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; pirmas</a>
            <a href="?page={{ page_obj.previous_page_number }}">ankstesnis</a>
        {% endif %}

        <span class="current">
            Puslapis {{ page_obj.number }} iš {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">kitas</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">paskutinis &raquo;</a>
        {% endif %}
    </span>
  </div>
</div>
{% endblock %}

autoservice/templates/autoservice/profilis.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-danger" role="alert">
            {{ message }}
        </div>
        {% endfor %}
        {% endif %}
      <div class="media">
        <img class="rounded-circle account-img" src="{{ user.profilis.nuotrauka.url }}">
        <div class="media-body">
          <h2 class="account-heading">{{ user.username }}</h2>
          <p class="text-secondary">{{ user.email }}</p>
        </div>
      </div>
       <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Profilio info</legend>
                {{ u_form|crispy }}
                {{ p_form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Atnaujinti</button>
            </div>
        </form>
    </div>
{% endblock content %}

autoservice/templates/autoservice/register.html
{% extends "base.html" %}

{% block content %}

    <div class="container register">
        <h3>Registracija</h3><br/>
        <form method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="username">Vartotojo vardas</label>
                <input name="username" type="text" class="form-control" id="username" aria-describedby="usernameHelp">
                <small id="usernameHelp" class="form-text text-muted">Iki 150 simbolių.</small>
            </div>
            <div class="form-group">
                <label for="exampleInputEmail1">El. paštas</label>
                <input name="email" type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
                <small id="emailHelp" class="form-text text-muted">Nesidalinsime su niekuo, nesiųsime jokio spamo.
                    Reikalingas naujam slaptažodžiui išsiųsti. </small>
            </div>
            <div class="form-group">
                <label for="password">Slaptažodis</label>
                <input name="password" type="password" class="form-control" id="password" aria-describedby="pwdHelp">
                <small id="pwdHelp" class="form-text text-muted">Ne mažiau, kaip 8 simboliai. Negali būti vien tik
                    skaičiai</small>
            </div>
            <div class="form-group">
                <label for="password2">Pakartoti slaptažodį</label>
                <input name="password2" type="password" class="form-control" id="password2" aria-describedby="pwd2Help">
            </div>
            <button type="submit" class="btn btn-primary register-button">Registruotis</button>
        </form>
        <p>Jeigu užsiregistravote anksčiau, <a href="/login"><strong>prisijunkite.</strong></a></p>
    </div>

{% endblock %}

autoservice/templates/autoservice/search.html
{% extends "base.html" %}

{% block content %}
<div class="container mt-4">
    <div class="row">
        <div class="col-md-6 mx-auto">  <!-- pridėjome Bootstrap klases čia -->
            <form method="GET" action="{% url 'search' %}">
                <div class="input-group mb-3">
                    <input type="text" name="query" class="form-control" placeholder="Įveskite paieškos terminą...">
                    <div class="input-group-append">
                        <button class="btn btn-outline-info" type="submit">Ieškoti</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <h5 class="mb-3">Paieškos pagal "{{query}}" rezultatai:</h5>
    {% if automobiliai %}
    <div class="list-group">
        {% for automobilis in automobiliai %}
        <a href="{% url 'automobilis_detail' automobilis.pk %}" class="list-group-item list-group-item-action">
            {{ automobilis.marke }} {{ automobilis.modelis }} ({{automobilis.klientas}})
        </a>
        {% endfor %}
    </div>
    {% else %}
    <div class="alert alert-warning" role="alert">
        Oops. Nieko neradome :(
    </div>
    {% endif %}
</div>
{% endblock %}

autoservice/templates/autoservice/service_detail.html
{% extends "base.html" %}

{% block content %}
  <h2 style="text-align: center; color: #333;">Paslauga</h2>
  <div style="margin-bottom: 20px; border: 1px solid #ddd; padding: 10px; border-radius: 5px;">
    <h6 style="margin: 0; color: #007BFF;">{{ service.name }}</h6>
    <p style="margin: 0; color: #6c757d;">Kaina: {{ service.price }} €</p>
  <h3 style="color: #333;">Užsakymo imitacija</h3>
  </div>
  <a href="{% url 'autoservice:services' %}" class="btn btn-primary">Grįžti į paslaugų sąrašą</a>
{% endblock %}

autoservice/templates/autoservice/service_list.html
{% extends "base.html" %}

{% block content %}
  <h2 style="text-align: center; color: #333;">Visos paslaugos</h2>
  <ul style="list-style-type: none; padding: 0;">
    {% for service in service_list %}
      <li style="margin-bottom: 20px; border: 1px solid #ddd; padding: 10px; border-radius: 5px;">
        <h6 style="margin: 0; color: #007BFF;">{{ service.name }}</h6>
        <p style="margin: 0; color: #6c757d;">Kaina: {{ service.price }} €</p>
        <a href="{% url 'autoservice:service_detail' service.id %}" style="display: inline-block; margin-top: 10px; padding: 5px 10px; background-color: #007BFF; color: white; text-decoration: none; border-radius: 5px;">Užsakyti</a>
      </li>
    {% empty %}
      <li style="color: #6c757d;">Nėra paslaugų</li>
    {% endfor %}
  </ul>
{% endblock %}