autoservice/urls.py
from django.urls import path
from . import views

app_name = 'autoservice'

urlpatterns = [
    path('', views.index, name='index'),
    path('cars/', views.CarListView.as_view(), name='cars'),
    path('car/<int:pk>', views.CarDetailView.as_view(), name='car_detail'),
    path('services/', views.ServiceListView.as_view(), name='services'),
    path('service/<int:pk>', views.ServiceDetailView.as_view(), name='service_detail'),
    path('orders/', views.OrderListView.as_view(), name='orders'),
    path('order/<int:pk>', views.OrderDetailView.as_view(), name='order_detail'),
    ]

learning/urls.py
from django.urls import path
from . import views

app_name = 'learning'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),

    path('categories/', views.CategoryListView.as_view(), name='categories'),
    path('category/<int:pk>', views.CategoryDetailView.as_view(), name='category_detail'),

    path('python/', views.PythonListView.as_view(), name='python'),
    path('python/<int:pk>', views.PythonDetailView.as_view(), name='python_detail'),

    path('django/', views.DjangoListView.as_view(), name='django'),
    path('django/<int:pk>', views.DjangoDetailView.as_view(), name='django_detail'),

    path('tasks/', views.TaskListView.as_view(), name='task_list'),
    path('task/<int:pk>', views.TaskDetailView.as_view(), name='task_detail'),

]

library/urls.py
from django.urls import path, include
from . import views

app_name = 'library'

urlpatterns = [
    path('', views.index, name='index'),
    path('authors/', views.authors, name='authors'),
    path('author/<int:author_id>/', views.author, name='author'),
    path('books/', views.BookListView.as_view(), name='books'),
    path('book/<int:pk>/', views.BookDetailView.as_view(), name='book_detail'),
    path('search/', views.search, name='search'),
    path('mybooks/', views.LoanedBooksByUserListView.as_view(), name='my_borrowed'),
    path('register/', views.register, name='register')

]

mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
    path('learning/', include('learning.urls')),
    path('', RedirectView.as_view(url='/learning/')),
    path('library/', include('library.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('autoservice/', include('autoservice.urls')),
    path('users/', include('users.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = 'Tinklapio valdymas'

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('profile/', views.profile, name='profile'),
    path('about/', views.about, name='about'),
    path('facebook_login/', views.facebook_login, name='facebook_login'),
    path('google_login/', views.google_login, name='google_login'),

]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="lt">
<head>
    <!-- Meta duomenys -->
    <meta charset="UTF-8">
    <title>{% block title %}Programavimas{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Bootstrap CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <!-- Papildomas stilių failas -->
    <link rel="stylesheet" href="{% static 'css/stylesheet.css' %}">

</head>
<body>
<!-- Navigacinis meniu -->
<nav class="navbar navbar-expand-lg example">
    <!-- Logotipas ir pagrindinė nuoroda -->
    <a class="navbar-brand" href="{% url 'learning:index' %}"><span class="text-primary fs-3 ms-2 fw-bolder">Django</span></a>

    <!-- Mygtukas mobiliajam meniu -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <!-- Pagrindinis užrašas -->
    <h2 class="text-center" style="font-size: 30px; opacity: 0.4;">&copy; 2024 DEMO VERSIJA</h2>

    <!-- Navigacijos meniu -->
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ml-auto">
            <!-- Nuorodos į projektus -->
            <li class="nav-item">
                <a class="nav-link" href="{% url 'library:index' %}">Projektas: Biblioteka</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'autoservice:index' %}">Projektas: Autoservisas</a>
            </li>

            <!-- Vartotojo autentifikacijos nuorodos -->
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:profile' %}">{{ user.get_username }}</a>
                </li>
                <li class="nav-item">
                    <form method="post" action="{% url 'logout' %}" class="form-inline">
                        {% csrf_token %}
                        <input type="hidden" name="next" value="/learning">
                        <button type="submit" class="btn btn-light">Atsijungti</button>
                    </form>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login' %}?next={{ request.path }}">Prisijungti</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:register' %}">Registruotis</a>
                </li>
            {% endif %}
        </ul>
    </div>
</nav>

<!-- Pagrindinis turinys -->
<main class="container mt-4">
    <!-- Pranešimų atvaizdavimas -->
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-info">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}

    <!-- Dinaminis turinys -->
    {% block content %}
    <!-- Čia bus įterptas pagrindinio puslapio turinys -->
    {% endblock content %}
</main>

<!-- Poraštė -->
{% block footer %}
<footer class="footer mt-auto py-3">
    <div class="container">
        <div class="row">
            <!-- Poraštės nuorodos -->
            <div class="col-md-4">
                <h5>Nuorodos</h5>
                <ul>
                    <li><a href="{% url 'users:about' %}">Apie mus</a></li>
                    <li><a href="#">Naudojimosi sąlygos</a></li>
                </ul>
            </div>

            <!-- Kontaktinė informacija -->
            <div class="col-md-4">
                <h5>Kontaktai</h5>
                <p>El. paštas: jevgen.vasiljevas@gmail.com</p>
                <p>Telefonas: +370 646 41835</p>
            </div>
            <!-- Socialiniai tinklai -->
            <div class="col-md-4">
                <h5>Socialiniai tinklai</h5>
                <a href="{% url 'users:facebook_login' %}">Facebook</a><br>
                <a href="{% url 'users:google_login' %}">Google</a><br>
            </div>
        </div>

        <!-- Autorių teisės -->
        <div >
                <p>&copy; <script>document.write(new Date().getFullYear());</script> Demonstracinis tinklapis. Visos teisės saugomos.</p>

</footer>
{% endblock footer %}

<!-- JavaScript failai -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>